[package]
name = "pbz"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Command-line interface for pbzarr"
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
flate2 = "1.1"
indicatif-log-bridge = "0.2"
log = "0.4"
noodles-bgzf = "0.48"
pbzarr = { path = "../pbzarr" }
pbzarr-readers = { path = "../pbzarr-readers" }
rayon = "1"

[dev-dependencies]
ndarray = "0.17"
noodles-bgzf = { version = "0.48", features = ["libdeflate"] }
noodles-core = "0.20"
noodles-csi = "0.57"
noodles-tabix = "0.63"
tempfile = "3"
