name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.70.1
          cache: true

      - run: pixi run test

      - run: pixi run clippy

      - run: pixi run fmt-check
